function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------

augmenter = imageDataAugmenter('RandRotation',[0 360],...
    'RandScale',[0.5 1],...
    'RandXTranslation',[-10 10],'RandYTranslation',[-10 10]);

newIa=augment(augmenter,im);
newIa1=augment(augmenter,im);
newIa2=augment(augmenter,im);

results.newIa=newIa;
results.newIa1=newIa1;
results.newIa2=newIa2;
%--------------------------------------------------------------------------
